### ISSUE TITLE
电子邮件发送

### ISSUE THREAD

**Issue by Froom939** [A10ha/EmailSender#1]
可以出一个详细的配置例子吗？我打包完成后一直报错    535

**Comment by A10ha** [comment]
smtplib.SMTPAuthenticationError: (535, ‘Error: authentication failed’)
你用的密码不对吧，常规的邮服是要用SMTP授权码的，除非你是自建的邮服。

**Comment by Froom939** [comment]
大佬能求个联系方式吗？

**Comment by A10ha** [comment]
你是用的什么SMTP服务器呢？如果是网易邮箱、或者qq邮箱需要开启SMTP协议，然后生成客户端授权码，在密码位置填写你生成的客户端授权码。
