### ISSUE TITLE
接收邮件的时候，会显示真实的发件人地址

### ISSUE THREAD

**Issue by littleheary** [A10ha/EmailSender#2]
测试的时候，发现发送邮件的时候，会显示真正的发件人地址。这个是否可以代码调整，然后新发布一份文件嘞？
或者是说我操作不当？请大佬赐教。
下图是分别使用foxmail打开和web打开的不同的提示
![image](https://github.com/A10ha/EmailSender/assets/26987382/a49afe58-a6e4-42ad-aa59-c38d09c57b52)
![image](https://github.com/A10ha/EmailSender/assets/26987382/f16a62c4-f0a5-4b68-8a98-c9c9c4bb1a75)

**Comment by A10ha** [comment]
配置发送人信息参数实现发件人信息伪造，有些邮件管理客户端会存在代发字段。

**Comment by A10ha** [comment]
这个建议还是不要伪造发件人，目前没想到办法用代码解决这个问题。
